name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install libxrandr
      run: apt install -y libxrandr-dev

    - name: Updating submodules
      run: git submodule update --init --recursive

    - name: Create build directory
      run: mkdir build

    - name: Generate cmake files
      run: |
        cd build
        cmake ..

    - name: Build using make
      run: |
        cd build
        make
      
