name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-ubuntu-pkg:
    name: Build Ubuntu Package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update repo information about packages
      run: sudo apt update

    - name: Install dependencies
      run: |
        sudo apt install -y libxrandr-dev \
                            libxinerama-dev \
                            libxcursor-dev \
                            libxi-dev \
                            libgl-dev \
                            libglfw3-dev \
                            libopenal-dev \
                            libglm-dev

    - name: Updating submodules
      run: git submodule update --init --recursive

    - name: Generate build files
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Compile
      run: |
        cd build
        make game

    - name: Install files
      run: |
        cd build
        DESTDIR="../dist/debian" make install

    - name: Generate package
      run: |
        dpkg-deb --build dist/debian
        mv dist/debian.deb engine.deb

    - name: Upload build to workflow
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: engine-ubuntu-${{ github.sha }}
        path: engine.deb

  install-ubuntu-pkg:
    name: Install Ubuntu Package
    needs: build-ubuntu-pkg
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: engine-ubuntu-${{ github.sha }}

    - name: Update repo information about packages
      run: sudo apt update

    - name: Install package
      run: sudo dpkg -i engine.deb

    # - name: Test package
    #   run: engine --version
