name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-ubuntu-deb:
    name: Build Ubuntu .deb
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update repo information about packages
      run: sudo apt update

    - name: Install dependencies
      run: sudo apt install -y libxrandr-dev \
                               libxinerama-dev \
                               libxcursor-dev \
                               libxi-dev \
                               libgl-dev

    - name: Updating submodules
      run: git submodule update --init --recursive

    - name: Create build directory
      run: mkdir build

    - name: Generate cmake files
      run: |
        cd build
        cmake ..

    - name: Build using make
      run: |
        cd build
        make
