name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-ubuntu-deb:
    name: Build Ubuntu Package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update repo information about packages
      run: sudo apt update

    - name: Install dependencies
      run: |
        sudo apt install -y libxrandr-dev \
                            libxinerama-dev \
                            libxcursor-dev \
                            libxi-dev \
                            libgl-dev

    - name: Updating submodules
      run: git submodule update --init --recursive

    - name: Generate build files
      run: cmake -S . -B build

    - name: Compile
      run: cmake --build build -t game
